import type { Metadata } from "next";
import GlobalHeader from "@/components/GlobalHeader/GlobalHeader";
import GlobalFooter from "@/components/GlobalFooter/GlobalFooter";
import { helveticaNeue, liberationSans } from "@/fonts";
import { AppProvider } from "@/context/AppContext";
import { classNames } from "@/utils";
import Region from "@/components/Region/Region";
import { RegionsProvider } from "@/context/RegionContext";
import BaseLayout from "@/components/BaseLayout/BaseLayout";
import Sticky from "@/components/Sticky/Sticky";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "PMC | Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProvider>
      <RegionsProvider>
        <html
          lang="en"
          className={classNames(
            liberationSans.variable,
            helveticaNeue.variable,
          )}
          >
            <head>
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1, shrink-to-fit=no"
              />
            </head>
          <body>
            <BaseLayout
              top={
                <Sticky name="globalHeader" hide>
                  <Region name="globalHeader">
                    <GlobalHeader />
                  </Region>
                </Sticky>
              }
              middle={
                <Region name="main">
                  <main>{children}</main>
                </Region>
              }
              bottom={
                <Region name="globalFooter">
                  <GlobalFooter />
                </Region>
              }
            />
          </body>
        </html>
      </RegionsProvider>
    </AppProvider>
  );
}
